2017-10-17 22:45:32,429 - WARNING - Keyfile had insecure permissions, but there were no enabled keys.
2017-10-17 22:45:33,513 - ERROR - There was a problem testing for a Namecoin daemon. Hiding the Fetch Namecoin ID button
2017-10-17 22:45:33,584 - WARNING - No notification.message plugin found
2017-10-17 22:45:38,590 - WARNING - No notification.sound plugin found
2017-10-17 22:52:17,107 - WARNING - Keyfile had insecure permissions, but there were no enabled keys.
2017-10-17 22:52:58,184 - ERROR - Got signal 15 in PoolWorker-1/singleWorker
2017-10-17 22:52:58,242 - ERROR - Fast PoW got StopIteration
2017-10-18 02:16:33,334 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:16:33,335 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:17:32,480 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:17:32,482 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:21:14,604 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:21:14,604 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:22:01,341 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:22:01,342 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:33:09,724 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:33:09,726 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:41:58,069 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:41:58,069 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:51:24,183 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 02:51:24,184 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 19:25:03,625 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 19:25:03,625 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 19:27:26,911 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 19:27:26,911 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:20:15,019 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:20:15,019 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:37:26,174 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:37:26,174 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:39:02,868 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:39:02,868 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:54:20,042 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:54:20,042 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:54:22,404 - ERROR - Got signal 2 in MainProcess/MainThread
2017-10-18 22:54:22,405 - ERROR - Got signal 2
2017-10-18 22:56:10,984 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 22:56:10,986 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 23:08:59,578 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-18 23:08:59,579 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 03:23:29,063 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 03:23:29,065 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 21:03:50,992 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 21:03:50,993 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 21:44:05,973 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 21:44:05,974 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 21:45:58,990 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 21:45:58,992 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:05:48,078 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:05:48,078 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:11:04,714 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:11:04,716 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:12:28,457 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:12:28,459 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:14:02,322 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:14:02,322 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:14:16,427 - ERROR - Got signal 2 in MainProcess/MainThread
2017-10-19 22:14:16,430 - ERROR - Got signal 2
2017-10-19 22:15:18,233 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:15:18,233 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:31:01,217 - ERROR - 81.105.101.129:8444 error: 2, Too many connections from your IP. Closing connection.
2017-10-19 22:31:29,582 - ERROR - Fast PoW got StopIteration
2017-10-19 22:45:56,961 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-19 22:45:56,961 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 19:26:39,592 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 19:26:39,594 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 19:31:18,292 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 19:31:18,292 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 19:41:48,365 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 19:41:48,367 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 19:45:48,538 - ERROR - Got signal 2 in MainProcess/MainThread
2017-10-21 19:45:48,538 - ERROR - Got signal 2
2017-10-21 19:49:17,128 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 19:49:17,130 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:26:37,648 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:26:37,648 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:29:39,868 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:29:39,871 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:32:50,594 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:32:50,595 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:32:52,026 - ERROR - Got signal 2 in MainProcess/MainThread
2017-10-21 20:32:52,028 - ERROR - Got signal 2
2017-10-21 20:32:57,496 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:32:57,496 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:35:23,766 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:35:23,767 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:36:51,384 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:36:51,384 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:38:08,944 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:38:08,944 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:48:01,515 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:48:01,516 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:50:52,555 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:50:52,555 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:54:11,934 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 20:54:11,936 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:01:21,953 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:01:21,953 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:06:08,380 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:06:08,381 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:07:16,548 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:07:16,549 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:14:20,825 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:14:20,826 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:15:56,789 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:15:56,789 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:17:51,937 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:17:51,937 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:19:29,092 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:19:29,092 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:22:20,148 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:22:20,150 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:31:26,075 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:31:26,076 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:32:54,887 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 21:32:54,888 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:11:51,371 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:11:51,371 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:13:29,910 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:13:29,911 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:15:40,520 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:15:40,522 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:49:06,387 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:49:06,388 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:50:44,634 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:50:44,634 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:53:32,246 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:53:32,246 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:54:51,963 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 22:54:51,963 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 23:09:13,381 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 23:09:13,381 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 23:15:00,561 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 23:15:00,562 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 23:19:31,438 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-21 23:19:31,440 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:01:19,457 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:01:19,460 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:06:11,200 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:06:11,201 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:09:20,392 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:09:20,394 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:10:32,696 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:10:32,697 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:13:27,618 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:13:27,619 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:50:28,286 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:50:28,286 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:52:31,838 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-22 23:52:31,838 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:08:31,529 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:08:31,529 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:12:09,798 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:12:09,799 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:52:40,065 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:52:40,066 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:57:02,538 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:57:02,539 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:58:58,898 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 00:58:58,900 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 01:01:08,390 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 252, in init
    bso = ctypes.WinDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
2017-10-23 01:01:08,391 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "C:\Users\VICTOR-PC\Documents\GitHub\taskhive-project\taskhive\src\bitmessage\proofofwork.py", line 262, in init
    bso = ctypes.CDLL(os.path.join(paths.codePath(), "bitmsghash", bitmsglib))
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
